# Generated by Django 3.0.8 on 2020-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='couplemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bfname', models.CharField(max_length=50)),
                ('Gfname', models.CharField(max_length=50)),
                ('probofmarr', models.IntegerField()),
            ],
        ),
    ]
